config/routes.rb
Rails.application.routes.draw do
  resources :recipe_books, only: [:new, :create, :index, :show]
  resources :users, only: [:new, :create]
  resources :password_resets, only: [:create, :new, :edit, :update]
  
  # Session routes for login/logout
  get '/login', to: 'sessions#new', as: :login
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: :logout

  # Recipe routes
 resources :recipes do
    collection do
      post 'scrape'
      get :search
    end
  member do
    get :scale
  end
end
  # Root route
  root "pages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cookbase" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>    
  </head>
      <div class="flash-messages">
      <% flash.each do |key, message| %>
        <div class="p-4 mb-4 text-sm rounded-lg flex items-center justify-between <%= key == 'notice' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800' %>">
          <span class="flex-grow"><%= message %></span>
          <button class="text-xl font-bold text-gray-500 hover:text-gray-800 ml-4" onclick="this.parentElement.remove()">×</button>
        </div>
      <% end %>
    </div>

  <nav class="w-full bg-white p-4">
    <!-- Logo container, centered on mobile, left-aligned on larger screens -->
    <div class="container mx-auto flex items-center justify-between">
      <div class="w-full flex justify-start">
        <%= link_to image_tag('cookbase.svg', class: 'mt-2 w-36 sm:w-40 md:w-48'), root_path %>

      </div>
      <button id="mobile-search-toggle" class="sm:hidden text-gray-800 focus:outline-none">
        <svg class="w-8 h-8 mx-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-4.35-4.35M16.65 10.65A6.35 6.35 0 1010.65 16.65 6.35 6.35 0 0016.65 10.65z"></path>
        </svg>
      </button>
      <!-- Hamburger Icon for Mobile -->
      <button id="menu-toggle" class="sm:hidden text-gray-800 hover:text-gray-600 focus:outline-none ml-auto">
        <svg class="w-8 h-8 mx-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
        </svg>
      </button>


      <!-- Navigation Links for Desktop -->
      <div class="flex items-center space-x-4">
        <!-- Desktop Links (hidden on mobile) -->
        <div class="hidden sm:flex space-x-6 text-gray-800">
          <% if logged_in? %>
            <%= link_to 'My Recipes', recipes_path, class: 'px-3 py-2 rounded-lg whitespace-nowrap hover:text-gray-600' %>
            <%= link_to 'Logout', logout_path, method: :delete, class: 'px-3 py-2 rounded-lg hover:text-gray-600' %>
          <% else %>
            <%= link_to 'Login', login_path, class: 'px-3 py-2 rounded-lg hover:bg-gray-100 hover:text-gray-600' %>
          <% end %>
        </div>

      </div>
    </div>

    <!-- Mobile Menu  -->
    <div id="mobile-menu" class="hidden sm:hidden bg-white w-full mt-2">
      <% if logged_in? %>
        <%= link_to 'My Recipes', recipes_path, class: 'block text-gray-800 hover:bg-gray-100 py-2 px-4 transition ease-in-out duration-200' %>
        <%= link_to 'Logout', logout_path, method: :delete, class: 'block text-gray-800 hover:bg-gray-100 py-2 px-4 transition ease-in-out duration-200' %>
      <% else %>
        <%= link_to 'Login', login_path, class: 'block text-gray-800 hover:bg-gray-100 py-2 px-4 transition ease-in-out duration-200' %>
      <% end %>
      <!-- Mobile Search Icon (hidden on larger screens) -->
    </div>
  </nav>

  <% if logged_in? %>
    <!-- Full-Screen Search Overlay -->
    <div id="mobile-search-overlay" class="fixed inset-0 bg-gray-800 bg-opacity-75 z-50 hidden flex items-center justify-center">
      <div class="bg-white p-6 rounded-lg w-11/12 max-w-md">
        <h2 class="text-lg font-semibold mb-4">Search Recipes</h2>
        <%= form_with url: search_recipes_path, method: :get, class: "search-form", id: "recipe-search-form", data: { turbo_frame: "search_results" } do %>
          <!-- Search Query -->
          <%= text_field_tag :query, params[:query], placeholder: "Search recipes...", class: "search-input w-full border border-gray-300 rounded p-2 focus:ring focus:ring-cookblue-200 focus:outline-none" %>
        <% end %>

        <!-- Tags Input or Display -->
        <div id="tag-container" class="mt-4">
          <% if params[:tags].present? %>
            <p>
            <%= link_to "Clear All Tags", search_recipes_path, data: { turbo_frame: "search_results" } %>
            </p>
          <% end %>
          <div class="flex flex-wrap gap-2 mt-2">
            <h2 class="text-lg font-semibold text-gray-700">Tags</h2>
            <% current_user.recipes.tag_counts_on(:tags).each do |tag| %>
              <span class="<%= tag_color(tag.name) %> text-sm font-medium px-3 py-1 rounded">
                <% if params[:tags]&.include?(tag.name) %>
                  <!-- Remove tag from filter -->
                  <%= link_to "(X) #{tag.name}", search_recipes_path(query: params[:query], tags: params[:tags] - [tag.name]) %>
                <% else %>
                  <!-- Add tag to filter -->
                  <%= link_to tag.name, search_recipes_path(query: params[:query], tags: (params[:tags] || []) + [tag.name]) %>
                <% end %>
              </span>
            <% end %>
          </div>
        </div>


        <button id="mobile-search-close" class="mt-4 px-4 py-2 bg-gray-800 text-white rounded-md">Close</button>
      </div>
    </div>


  <% end %>

  <body class="bg-gray-100 sm:bg-white">
    <%= turbo_include_tags %>
    <div class="<%= params[:controller] == 'recipes' && (params[:action] == 'index' || params[:action] == 'search') ? 'w-full' : 'container mx-auto mb-24' %>">
      <%= yield %>
    </div>
  </body>
</html>